### ISSUE TITLE
Support `cause` in Error constructor 

### ISSUE THREAD

**Issue by erfanium** [fastify/fastify-error#112]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

it would be great to be able to use cause option in fastify errors as well

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause

### Example

```js
const jsError = new Error("hey", { cause: new Error("cause") }) // supported by js
const fError = new FASTIFY_ERROR("hey", { cause: new Error("cause") }); // not supported
```

**Comment by Uzlopak** [comment]
Maybe when we drop node 14 :+1:

**Comment by mcollina** [comment]
There is no need to wait, we could implement it ourselves in this repo.

**Comment by erfanium** [comment]
How could we support this without breaking change?
currently, the Error class constructor receives rest arguments. so we can't add new argument for options.

**Comment by mcollina** [comment]
Something like: 

```js
// function createError (code, message, statusCode = 500, Base = Error, hasCause = false)
const MyErorr =  createError('ABC', 'something', Error, true)
```

Which is backward compatible.

At some point, we would need to drop (!) the positional arguments and use an object.

**Comment by Uzlopak** [comment]
Is it really preferable to pass in an object?

I created once https://github.com/fastify/fastify-error/pull/103 were the formatter would have been generated on creation of the ErrorConstructor. If we never had rest arguments, the serializer would be faster. And tbh. I dont know how the { args } would work. Also `new MyError({ message, args, cause })` doesnt make sense, because we have currently no "message" parameter.

**Comment by jsumners** [comment]
> Is it really preferable to pass in an object?

In my opinion, all functions should be declared `function ({ ...input }) {}` going forward. It is effectively a named parameters implementation and the developer experience benefit far outweighs any negligible performance gains.

> Also `new MyError({ message, args, cause })` doesnt make sense, because we have currently no "message" parameter.

Technically, the signature is `MyError([messageParam1], ..., [messageParamX])`. The only requirement the `MyError` constructor carries over from the standard `Error` constructor is that it can be invoked with or without `new`. I want to keep that, but I am all for making the parameters an object.

**Comment by Uzlopak** [comment]
Exactly. So it would something like 

MyError({args, cause, statusCode}) and so on. But it would make sense then to change the format string to a simple serializer.

E.g.

```js
const createError = require('@fastify/error')
const MyError = createError('ERROR_CODE', 'Hello %entity')
console.log(new MyError({entity: 'world'})) // error.message => 'Hello world'
```

**Comment by jsumners** [comment]
I don't think so. It's easier all around to have `MyError({ formatValues: ['a', 'b', 42] })` or, if someone really wants to re-supply the names, `MyError({ formatValues: { a: 'a', b: 'b', answer: 42 })`.

**Comment by Uzlopak** [comment]
It feels like the whole aspect of fast error instanciation get lost, when we pass objects and arrays.

**Comment by jsumners** [comment]
Pretty sure that's never been the goal of this module. I believe its purpose is for generating standard errors with error codes.

**Comment by mcollina** [comment]
> 
It feels like the whole aspect of fast error instanciation get lost, when we pass objects and arrays.

There is absolutely nothing fast in creating an error due to the stacktrace requirement. Fastify kinds of requires the use of Errors for certain patterns and maybe we might want to provide a few fast-paths there.

**Comment by DanieleFedeli** [comment]
I will pick this up, I will open a draft PR soon

**Comment by erfanium** [comment]
Thanks guys for implementing this!
