### ISSUE TITLE
Message "%s" does not resolve to "" when argument is not passed into Error

### ISSUE THREAD

**Issue by domarp-j** [fastify/fastify-error#133]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.0

### Node.js version

22.3.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04.6

### Description

I'm not sure if this is a bug or a feature request. Please correct me one way or the other.

I'm trying to support the following functionality:

```ts
export const Unauthorized = createError("MY_UNAUTHORIZED", "%s", 403);

throw new Unauthorized("You cannot do this")
// { "code": "MY_UNAUTHORIZED", "Bad Request", "message": "You cannot do this", "statusCode": 403 } 

throw new Unauthorized()
// { "code": "MY_UNAUTHORIZED", "Bad Request", "message": "", "statusCode": 403 } 
```

However, the second case resolves to:

```ts
throw new Unauthorized()
// { "code": "MY_UNAUTHORIZED", "Bad Request", "message": "%s", "statusCode": 403 } 
// Note the "%s" in the message.
```

This is consistent with how `node:util`'s `format` works, but I don't think it's useful here. I think a blank message, rather than "%s", is preferable in this scenario.

**Comment by climba03003** [comment]
It is actually using the `node:util`, I believe the behavior is unlikely to be changed.

https://github.com/fastify/fastify-error/blob/d06ad6a9a80b75dbd6f22eb86be94b588a9a1dde/index.js#L30

**Comment by domarp-j** [comment]
There isn't a possibility of using some other string interpolation method? Having '%s' as the message seems like a reasonably common use case, and `node:util`'s implementation doesn't seem sufficient.

**Comment by Uzlopak** [comment]
What is blocking you from passing an empty string to the constructor?

**Comment by domarp-j** [comment]
Fair question. I think it's more idiomatic and instinctual to write `throw new Unauthorized()` than `throw new Unauthorized('')`. The latter feels a bit more awkward, IMO. And it's another thing devs will have to remember, unless an ESLint rule enforces it or something similar.

**Comment by Uzlopak** [comment]
There is actually no reason to set "%s" as value when creating the error, also. util.format will just append any strings anyway...

**Comment by domarp-j** [comment]
@Uzlopak I must be missing something basic here. How can I do the following:

```
const MyError = createError('MY_CODE', ??, 400)

throw new MyError() // message = ""
throw new MyError("something broke") // message = "something broke"
```

What should I pass in as `message` to `createError()` to make this happen? I think this is a reasonable use case, but I can't seem to get `node:util` to enable this for me. Yes, I know I can pass in an empty string and use `%s` as a message, but I don't think that should be necessary.

**Comment by jsumners** [comment]
https://github.com/fastify/fastify-error/blob/master/test/index.test.js#L6-L17

**Comment by domarp-j** [comment]
@jsumners Unfortunately that doesn't cover my use case. I don't want any other text in the message I pass into the created Error.

**Comment by domarp-j** [comment]
I have a PR that describes the issue: https://github.com/fastify/fastify-error/pull/134
