### ISSUE TITLE
FastifyError is not exported, but declared in the typings as concrete

### ISSUE THREAD

**Issue by biro456** [fastify/fastify-error#21]
## 🐛 Bug Report

The typings clearly declare a concrete value for `FastifyError`, but in runtime the value is `undefined`.

From what I could gather, `FastifyError` was never exported from the `index.js`, but #9 included it as a concrete value in `index.d.ts` for some reason.

## To Reproduce

Compile and execute this script with TypeScript.

```typescript
import { FastifyError } from 'fastify-error';

console.info(FastifyError);
```

## Expected behavior

The `console.info` should log the value of the FastifyError pseudo-class.

## Your Environment

- *node version*: 14.16.0
- *fastify version*: 3.14.2
- *fastify-error version*: 0.3.0

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by climba03003** [comment]
No, `console.info` return `undefined` is the correct behavior. When you look at `index.js` it never export something call `FastifyError`.
`FastifyError` is only the types for you to decorate the `Error`.
