### ISSUE TITLE
ValidationResult.params type is not always correct

### ISSUE THREAD

**Issue by laurieboyes** [fastify/fastify-error#3]
## 🐛 Bug Report

The `params` property of `ValidationResult` is typed as `Record<string, string>` (https://github.com/fastify/fastify-error/blob/master/index.d.ts#L11), however, when a request validation error occurs because a value is not a valid option within an enum, there is an `allowedValues` param on the validation result, which is an array.

If you follow along a bit you can see where this occurs in this file (apologies, I can’t track down the thing that generates it) https://github.com/fastify/fast-json-stringify/blob/master/schema-validator.js#L1213.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
