### ISSUE TITLE
Capability to send objects within errors

### ISSUE THREAD

**Issue by TriStarGod** [fastify/fastify-error#35]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

To send objects with errors to client without stringifying them.

ATM, I implement this by creating an Error with code "C_VALIDATION" and a random fixed length message (since it won't let me send a blank message). Then, when my custom validation fails for a specific use case, I would call that error and pass an object with properties that need to be rectified by the client. After receiving the error and confirming the "C_VALIDATION" code, the client would remove the random message and convert the stringified object back into an object. Seems like a lot of unnecessary work to send an object with the error.

## Motivation

Please outline the motivation for the proposal.
When sending errors from the server, I may have one or more properties that may need further validation that AJV can't easily handle.

## Example

Please provide an example for how this feature would be used.

I may want to send an error object like
{ username: "INUSE", sec: "MISMATCH" }

**Comment by climba03003** [comment]
You can send it directly like
```js
fastify.get('/', function(_, reply) {
  reply.code(400).send({ username: "INUSE", sec: "MISMATCH" })
})
```

If you prefer to throw an error but retain the original behavior on error handling.
```
fastify.get('/', function(_, reply) {
  throw { username: "INUSE", sec: "MISMATCH" }
})

fastify.setErrorHandler(function(err, _, reply) {
  if(err.statusCode) {
    reply.code(err.statusCode).send(err)
  } else {
    reply.code(400).send(err)
  }
})
```

**Comment by TriStarGod** [comment]
@climba03003 I tried as you suggested with

```
// on the server
const err = new CValidationError();
 (err as any).errors = {
  username: "INUSE",
  sec: "MISMATCH",
 };
 throw err;

// on the client
data: {
 code: "C_VALIDATION",
 error: "Internal Server Error",
 message: "A",
 statusCode: 500,
}
```

I think fastify filters properties sent.

**Comment by climba03003** [comment]
> 
> 
> @climba03003 I tried as you suggested with
> 
> ```
> // on the server
> const err = new CValidationError();
>  (err as any).errors = {
>   username: "INUSE",
>   sec: "MISMATCH",
>  };
>  throw err;
> 
> // on the client
> data: {
>  code: "C_VALIDATION",
>  error: "Internal Server Error",
>  message: "A",
>  statusCode: 500,
> }
> ```
> 
> I think fastify filters properties sent.

You need to set a custom error handler.
```js
fastify.setErrorHandler(function(error, _, reply) {
  // you need extra check for the error object.
  reply.send(error.statusCode || 400).send(error)
})

**Comment by TriStarGod** [comment]
@climba03003 I researched bit more into error management in NodeJs and discovered throwing errors has a performance penalty. So, I redid all my error handling to use reply. I'm assuming this is the suggested way due to fastify's implementation but I never read that in docs.
