### ISSUE TITLE
Interpolation ignores falsey values and keeps %s in the message

### ISSUE THREAD

**Issue by bajtos** [fastify/fastify-error#67]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.4

### Plugin version

1.0.0

### Node.js version

16.13.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3

### Description

A request with a missing content type header produced a response with a bit cryptic error message.

```json5
{
  statusCode: 415,
  code: 'FST_ERR_CTP_INVALID_MEDIA_TYPE',
  error: 'Unsupported Media Type',
  message: 'Unsupported Media Type: %s'
}
```

Notice the `%s` placeholder in the message. It's not clear where is the placeholder coming from - is there perhaps a bug in fastify causing the placeholder to not be replaced? It's hard to tell for the API consumer.

I believe the problem is actually caused by missing `Content-Type` header in my API request.

- After adding content-type header to my request, the error is no longer presented.

 
- When sending invalid content-type value, the error message reports back the invalid value. 

    ```json5
    {
      statusCode: 415,
      code: 'FST_ERR_CTP_INVALID_MEDIA_TYPE',
      error: 'Unsupported Media Type',
      message: 'Unsupported Media Type: application/foobar'
    }
    ```

### Steps to Reproduce

A self-contained script to reproduce the error (just `npm install fastify`):

```js
import Fastify from 'fastify';
import http from 'http';

const fastify = Fastify();

fastify.route({
  method: 'POST',
  url: '/',
  async handler(req, reply) {
    console.log('request body', req.body);
    return { ok: true };
  },
});

await fastify.listen(3000);

const req = http.request({ method: 'POST', port: 3000 });

req.on('response', async (res) => {
  console.log(res.statusCode, res.statusMessage);

  res.setEncoding('utf-8');
  let body = '';
  res.on('data', (chunk) => (body += chunk));
  res.on('end', () => {
    console.log(JSON.parse(body));
    fastify.close();
  });
});

req.write('{"dummy": true}');
req.end();
```

Current output:

```
415 Unsupported Media Type
{
  statusCode: 415,
  code: 'FST_ERR_CTP_INVALID_MEDIA_TYPE',
  error: 'Unsupported Media Type',
  message: 'Unsupported Media Type: %s'
}
```

### Expected Behavior

**The error message does not contain `%s` placeholder. Instead, it should explain the user that the content-type header was missing (or set to an empty value).**

### Additional information

Here is an example script to show current handling of edge cases:

```js
import createError from 'fastify-error';
const CustomError = createError('DUMMY', 'Unsupported Media Type: %s');

console.log('undefined         ->  ', new CustomError(undefined).message);
console.log('null              ->  ', new CustomError(null).message);
console.log('<empty>           ->  ', new CustomError('').message);
console.log('application/json  ->  ', new CustomError('application/json').message);
```

Output:

```
undefined         ->   Unsupported Media Type: %s
null              ->   Unsupported Media Type: %s
<empty>           ->   Unsupported Media Type: %s
application/json  ->   Unsupported Media Type: application/json
```

**Comment by bajtos** [comment]
> Expected Behavior
>
> The error message does not contain %s placeholder. Instead, it should explain the user that the content-type header was missing (or set to an empty value).

Personally, I think it would be great if the error message can distinguish between different kinds of empty/false-like values. For example:

```
undefined           ->   Unsupported Media Type: <undefined>
null                ->   Unsupported Media Type: <null>
''                  ->   Unsupported Media Type: <empty string>
'application/json'  ->   Unsupported Media Type: "application/json"
```

Alternatively, we can report a completely different error message when the header is missing; and perhaps use JSON.stringify for the remaining cases.

```
undefined           ->   Cannot determine the content type of the request body. 
                         There was no "Content-Type" header provided by the client.
null                ->   Unsupported Media Type: null
''                  ->   Unsupported Media Type: ""
'application/json'  ->   Unsupported Media Type: "application/json"
```

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by bajtos** [comment]
@jsumners thank you for getting back to me so quickly! 🙇🏻‍♂️

I am happy to send a pull request!

AFAICT, the problem is caused by the following performance optimization:

https://github.com/fastify/fastify-error/blob/22ad1fc65f752ebf754e6838a45b299f7bc8c47d/index.js#L19-L28

The easiest fix is to remove that optimization, but I am not sure if that's acceptable?

I can try to find a different approach that will avoid the spread operator but provide the correct behaviour. How about the following implementation checking `arguments.length`?

```js
switch (arguments.length) {
   case 3:
     this.message = format(message, a, b, c)
     break
   case 2:
     this.message = format(message, a, b) 
     break
   case 1:
     this.message = format(message, a) 
     break
   case 0:
     this.message = message 
     break
   default:
     this.message = format(message, ...arguments)
} 
```

Do you have any advice on how to measure the performance impact of my changes? I don't see any benchmark in this repository.

**Comment by mcollina** [comment]
I would not worry too much about this change, go ahead and send a PR!
