### ISSUE TITLE
FastifyError type issue

### ISSUE THREAD

**Issue by inidzelsky** [fastify/fastify-error#8]
## 🐛 Bug Report

I decided to use `fastify-error` for improved error-handling. So, I followed the docs and used `new CustomError()`. WebStorm revealed the `This expression is not constructable. Type 'FastifyError' has no construct signatures.` alert. So, I tried to ignore it, but I got FastifyError type bug. 

## To Reproduce

```ts
  const token = this.cookies['X-Auth-Token'];
  const TokenError = createError('UNAUTHENTICATED', 'Invalid token', 401);

  if (!token) {
    throw new TokenError();
  }

  const payload = fastify.jwt.decode(token);

  if (payload) {
    const { user } = payload as JWT;

    if (!user) {
      throw new TokenError();
    }
    return user;
  } else {
    throw new TokenError();
  }
```

I expected the error with 401 status, but got 

```js
    res: {
      "statusCode": 500
    }
    err: {
      "type": "TypeError",
      "message": "fastify_error_1.default is not a function",
      "stack":
          TypeError: fastify_error_1.default is not a function
    }

```

When I looked at the FastifyError implementation, I found the only interface
```ts
export interface FastifyError extends Error {
  code: string
  statusCode?: number
  validation?: ValidationResult[]
}
```

But if I console.log what `createError()` returns, I saw

```ts
function FastifyError (a, b, c) {
    if (!(this instanceof FastifyError)) {
      return new FastifyError(a, b, c)
    }
    Error.captureStackTrace(this, FastifyError)
    this.name = 'FastifyError'
    this.code = code

    // more performant than spread (...) operator
    if (a && b && c) {
      this.message = format(message, a, b, c)
    } else if (a && b) {
      this.message = format(message, a, b)
    } else if (a) {
      this.message = format(message, a)
    } else {
      this.message = message
    }

```

## Your Environment

- *node version*: 12.18.1
- *fastify version*: 3.8.0
- *os*: Mac
- *typescript*: 4.0.5

**Comment by mcollina** [comment]
@fastify/typescript can you take a look?

**Comment by Ethan-Arrowood** [comment]
What is your tsconfig?

**Comment by L2jLiga** [comment]
Is not #6 solves this issue?

**Comment by erfanium** [comment]
@L2jLiga No, it's not a typescript error, it's runtime error

**Comment by mcollina** [comment]
Can you please provide a runnable example to reproduce your error?

**Comment by Ethan-Arrowood** [comment]
I suspect you are dealing with an cjs vs mjs issue - please post your tsconfig and a reproduction so I can give you more in site.
